// ============================================================================
// Root Project Configuration
// ============================================================================
rootProject.name = 'cics-java-liberty-restapp'

// ============================================================================
// Subprojects
// ============================================================================
include(':cics-java-liberty-restapp-app')
include(':cics-java-liberty-restapp-bundle')